name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  testing-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 1. Kodu Checkout Et
        uses: actions/checkout@v4

      - name: 2. Cypress Testlerini Başlat
        uses: cypress-io/github-action@v7
        with:
          browser: chrome

      - name: 3. Raporu Canlı Link Olarak Yayınla
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html

      - name: 4. Slack Ekibine Haber Ver
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: '🤖 Cypress E2E Test Sonucu'
          SLACK_MESSAGE: |
            *Branch*: `${{ github.ref_name }}`
            *Durum*: ${{ job.status }}
            Raporu görmek için: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
